// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StyleSync.Api.Common.Persistence;

#nullable disable

namespace StyleSync.Api.Common.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008091511_AddPreferredDesignerId")]
    partial class AddPreferredDesignerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StyleSync.Api.Common.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StyleSync.Api.Models.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DesignerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<string>("TermsSummary")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DesignerId");

                    b.HasIndex("ProjectRequestId");

                    b.HasIndex("QuoteId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("StyleSync.Api.Models.Quote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DesignerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAiGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeSummary")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignerId");

                    b.HasIndex("ProjectRequestId");

                    b.HasIndex("Status");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("StyleSync.Api.Models.QuoteItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId");

                    b.ToTable("QuoteItems");
                });

            modelBuilder.Entity("StyleSync.Api.Models.QuoteVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ContingencyAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DesignFee")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("LaborSubtotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("MaterialsSubtotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("QuoteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuoteId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("QuoteVersions");
                });

            modelBuilder.Entity("StyleSync.Api.Models.QuoteVersionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuoteVersionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("QuoteVersionId");

                    b.ToTable("QuoteVersionItems");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.DesignerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ListingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConcurrentProjects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<decimal>("PriceRangeMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceRangeMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RatePerSqFt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<List<string>>("ServiceCategories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("StyleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DesignerProfiles", (string)null);
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BudgetRangeLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientInitials")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CompletionStatusBadge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DesignerProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignerProfileId");

                    b.ToTable("PortfolioItems", (string)null);
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProgressPhoto", b =>
                {
                    b.Property<Guid>("ProgressPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid");

                    b.HasKey("ProgressPhotoId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("ProgressPhotos");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectMaterial", b =>
                {
                    b.Property<Guid>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("OrderedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaterialId");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("TaskId");

                    b.ToTable("ProjectMaterials");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectMilestone", b =>
                {
                    b.Property<Guid>("MilestoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MilestoneId");

                    b.ToTable("ProjectMilestones");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTask", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CascadedDelay")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("TaskId");

                    b.HasIndex("MilestoneId");

                    b.ToTable("ProjectTasks");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTimelineEvent", b =>
                {
                    b.Property<Guid>("TimelineEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TimelineEventId");

                    b.ToTable("ProjectTimelineEvents");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.TaskDependency", b =>
                {
                    b.Property<Guid>("TaskDependencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("PrerequisiteTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("TaskDependencyId");

                    b.HasIndex("PrerequisiteTaskId");

                    b.HasIndex("TaskId", "PrerequisiteTaskId")
                        .IsUnique();

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.MoodboardImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRequestId");

                    b.ToTable("MoodboardImages");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlagReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("FlaggedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("PaletteBaseHex")
                        .HasColumnType("text");

                    b.Property<string>("PaletteMode")
                        .HasColumnType("text");

                    b.Property<string>("PalettePresetId")
                        .HasColumnType("text");

                    b.Property<Guid?>("PreferredDesignerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomPhotoStorageKey")
                        .HasColumnType("text");

                    b.Property<string>("RoomPhotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("RoomSizeSqFt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FlaggedByUserId");

                    b.HasIndex("PreferredDesignerId");

                    b.HasIndex("RoomType");

                    b.HasIndex("Status");

                    b.HasIndex("ClientId", "Status");

                    b.ToTable("ProjectRequests");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.RequestAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("RequestAuditLogs");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.RequestStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ProjectRequestId");

                    b.ToTable("RequestStatusHistories");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.SuggestedPalette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRequestId");

                    b.ToTable("SuggestedPalettes");
                });

            modelBuilder.Entity("StyleSync.Api.Models.Contract", b =>
                {
                    b.HasOne("StyleSync.Api.Models.Quote", "Quote")
                        .WithOne("Contract")
                        .HasForeignKey("StyleSync.Api.Models.Contract", "QuoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("StyleSync.Api.Models.QuoteItem", b =>
                {
                    b.HasOne("StyleSync.Api.Models.Quote", "Quote")
                        .WithMany("Items")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("StyleSync.Api.Models.QuoteVersion", b =>
                {
                    b.HasOne("StyleSync.Api.Models.Quote", "Quote")
                        .WithMany("Versions")
                        .HasForeignKey("QuoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quote");
                });

            modelBuilder.Entity("StyleSync.Api.Models.QuoteVersionItem", b =>
                {
                    b.HasOne("StyleSync.Api.Models.QuoteVersion", "QuoteVersion")
                        .WithMany("Items")
                        .HasForeignKey("QuoteVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuoteVersion");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.DesignerProfile", b =>
                {
                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("StyleSync.Api.Modules.Designers.Models.DesignerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.PortfolioItem", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.Designers.Models.DesignerProfile", "DesignerProfile")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("DesignerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignerProfile");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProgressPhoto", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectExecution.Models.ProjectMilestone", "Milestone")
                        .WithMany("ProgressPhotos")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("Task");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectMaterial", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectExecution.Models.ProjectMilestone", "Milestone")
                        .WithMany("Materials")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Milestone");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTask", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectExecution.Models.ProjectMilestone", "Milestone")
                        .WithMany("Tasks")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.TaskDependency", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTask", "PrerequisiteTask")
                        .WithMany("Dependents")
                        .HasForeignKey("PrerequisiteTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTask", "Task")
                        .WithMany("Prerequisites")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrerequisiteTask");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.MoodboardImage", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", "ProjectRequest")
                        .WithMany("MoodboardImages")
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", b =>
                {
                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "FlaggedByUser")
                        .WithMany()
                        .HasForeignKey("FlaggedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "PreferredDesigner")
                        .WithMany()
                        .HasForeignKey("PreferredDesignerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("FlaggedByUser");

                    b.Navigation("PreferredDesigner");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", "ProjectRequest")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.SuggestedPalette", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", "ProjectRequest")
                        .WithMany("SuggestedPalettes")
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("StyleSync.Api.Models.Quote", b =>
                {
                    b.Navigation("Contract");

                    b.Navigation("Items");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("StyleSync.Api.Models.QuoteVersion", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.DesignerProfile", b =>
                {
                    b.Navigation("PortfolioItems");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectMilestone", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("ProgressPhotos");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectExecution.Models.ProjectTask", b =>
                {
                    b.Navigation("Dependents");

                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", b =>
                {
                    b.Navigation("MoodboardImages");

                    b.Navigation("StatusHistories");

                    b.Navigation("SuggestedPalettes");
                });
#pragma warning restore 612, 618
        }
    }
}
