// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StyleSync.Api.Common.Persistence;

#nullable disable

namespace StyleSync.Api.Common.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StyleSync.Api.Common.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.MoodboardImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRequestId");

                    b.ToTable("MoodboardImages");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CancelReason")
                        .HasColumnType("text");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlagReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FlaggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FlaggedByUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("boolean");

                    b.Property<string>("PaletteBaseHex")
                        .HasColumnType("text");

                    b.Property<string>("PaletteMode")
                        .HasColumnType("text");

                    b.Property<string>("PalettePresetId")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomPhotoStorageKey")
                        .HasColumnType("text");

                    b.Property<string>("RoomPhotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("RoomSizeSqFt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FlaggedByUserId");

                    b.HasIndex("RoomType");

                    b.HasIndex("Status");

                    b.HasIndex("ClientId", "Status");

                    b.ToTable("ProjectRequests");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.RequestAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("RequestAuditLogs");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.RequestStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ProjectRequestId");

                    b.ToTable("RequestStatusHistories");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.SuggestedPalette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRequestId");

                    b.ToTable("SuggestedPalettes");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.MoodboardImage", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", "ProjectRequest")
                        .WithMany("MoodboardImages")
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", b =>
                {
                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "FlaggedByUser")
                        .WithMany()
                        .HasForeignKey("FlaggedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("FlaggedByUser");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.RequestStatusHistory", b =>
                {
                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", "ProjectRequest")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.SuggestedPalette", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", "ProjectRequest")
                        .WithMany("SuggestedPalettes")
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRequest");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.ProjectRequests.Models.Entities.ProjectRequest", b =>
                {
                    b.Navigation("MoodboardImages");

                    b.Navigation("StatusHistories");

                    b.Navigation("SuggestedPalettes");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.ContractStub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesignerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.DesignerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AverageRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("ListingStatus")
                        .HasColumnType("integer");

                    b.Property<int>("MaxConcurrentProjects")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<decimal>("PriceRangeMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceRangeMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RatePerSqFt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<List<string>>("ServiceCategories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<List<string>>("StyleTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("DesignerProfiles", (string)null);
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.PortfolioItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BudgetRangeLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientInitials")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("CompletionStatusBadge")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("DesignerProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DesignerProfileId");

                    b.ToTable("PortfolioItems", (string)null);
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.DesignerProfile", b =>
                {
                    b.HasOne("StyleSync.Api.Common.Identity.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("StyleSync.Api.Modules.Designers.Models.DesignerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.PortfolioItem", b =>
                {
                    b.HasOne("StyleSync.Api.Modules.Designers.Models.DesignerProfile", "DesignerProfile")
                        .WithMany("PortfolioItems")
                        .HasForeignKey("DesignerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignerProfile");
                });

            modelBuilder.Entity("StyleSync.Api.Modules.Designers.Models.DesignerProfile", b =>
                {
                    b.Navigation("PortfolioItems");
                });
#pragma warning restore 612, 618
        }
    }
}
